import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dhaanyagunha",
  description: "Generated by create chintu & co.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <body>
        <Providers>
        <Header />
        <div className=" bg-[#d7e5d4] h-screen p-5">
          {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
